### ISSUE TITLE
Edit profile impossible if logged/registered with Facebook

### ISSUE THREAD

**Issue by Israel-Laguan** [mikenath223/Project-Building-Facebook#10]
# Problem
To update profile you want my password, something not possible if signed up with Facebook.

I entered, signed up with Facebook and in profile view I tried to update my info (not set automatically, because I signed up with FB and not in the sign up form). 

![Screenshot_20200209-115534](https://user-images.githubusercontent.com/36519478/74106304-a2810080-4b33-11ea-8abe-bd8288ac4701.png)

This cause me as an user to not update my profile as I can't provide my password from  Facebook.
# Suggestions

Or update without requesting password (dangerous) or ask password if not signed up with FB or some other method.

**Comment by mikenath223** [comment]
Created a new method on controller to request password from users not signed up through Facebook.

**Comment by Israel-Laguan** [comment]
I verified and it worked! 
![image](https://user-images.githubusercontent.com/36519478/74200769-ce84aa80-4c35-11ea-83d4-723225d5ffb8.png)
