### ISSUE TITLE
Add a link to New Post in home

### ISSUE THREAD

**Issue by Israel-Laguan** [mikenath223/Project-Building-Facebook#11]
# Problem

For a newcomer can be difficult to Create Post, and it will be better to give to users a helping hand. 

![Screenshot_20200209-121807](https://user-images.githubusercontent.com/36519478/74106668-ac583300-4b36-11ea-984c-c6c62519615c.png)

# Suggestion

Add a link to New Post form at the top of Home, like FB do.

**Comment by mikenath223** [comment]
Created new post form at top of post feed as suggested
