### ISSUE TITLE
Add like to Search Friends and to Create Post in User profile if not friend not posts

### ISSUE THREAD

**Issue by Israel-Laguan** [mikenath223/Project-Building-Facebook#12]
# Problem

When a new user enter her/his profile, and have no friends and no posts, would be great if there are links to the forms corresponding to Search Friends and New Post

![Screenshot_20200209-122536](https://user-images.githubusercontent.com/36519478/74106819-d0684400-4b37-11ea-83fa-f62e0fb29461.png)

**Comment by mikenath223** [comment]
-Added create new post form to post index view.
-Add a welcome template to same view with a find friends button.

**Comment by Israel-Laguan** [comment]
![image](https://user-images.githubusercontent.com/36519478/74200862-14417300-4c36-11ea-8b0d-ba6f76a11510.png)
Verified
