### ISSUE TITLE
In Search Friend view would be nice to add Name or email

### ISSUE THREAD

**Issue by Israel-Laguan** [mikenath223/Project-Building-Facebook#13]
Now we have to enter profile to see the user's name
![image](https://user-images.githubusercontent.com/36519478/74200621-7352b800-4c35-11ea-83c5-baa9218d53a4.png)

Maybe a possible solution is to use the email because is one sure thing, or something else to know who is who in Search Friend

**Comment by mikenath223** [comment]
User Name added to user index view.
